def test_text_nlp():
    return [
        "am palpitatii si am avut un infarct miocardic",
        "sunt obosit cronic si am migrene frecvente",
        "am colesterol crescut si diabet de tip 2",
        "am probleme cu tiroida si noduli tiroidieni",
        "am constipatie si balonare de mai multe luni",
        "am menopauza precoce si ovare polichistice",
        "am hipertensiune si tahicardie ocazionala",
        "am dureri de cap severe si insomnie",
        "am ficat gras si steatoza hepatica",
        "am sindrom metabolic si obezitate",
        "am retentie de apa si edeme",
        "am apnee in somn si dificultati de respiratie",
        "am dureri articulare si inflamatie la genunchi",
        "am depresie si anxietate cronica",
        "am arsuri la stomac frecvente si reflux gastroesofagian",
        "am amorteala la maini si furnicaturi",
        "am probleme cu vederea si glaucom",
        "am diabet zaharat si neuropatie periferica",
        "am probleme cu rinichii si hipertensiune arteriala",
        "am alergii sezoniere si rinita alergica",
        "am dificultati de concentrare si oboseala mentala",
        "am dureri musculare si fibromialgie",
        "am probleme cu tiroida si hipotiroidism",
        "am episoade de vertij si pierderi de echilibru",
        "am insomnie si tulburari de somn",
        "am arsuri la stomac si gastrita cronica",
        "am sensibilitate dentara si dureri la masele",
        "am migrene si ameteli frecvente",
        "am dificultati de respiratie si astm bronsic",
        "am infectii urinare repetate",
        "am probleme cu ficatul si hepatita cronica",
    ]
